project_id: "PVT_kwDOA4EWJM4AwluD"

parent_issue:
  title: "Release Readiness Tracker"
  labels:
    - "M-tracking"

issues:
  - title: "Code complete"
  - title: "Cut contracts release"
  - title: "Integrate with OPCM/OP Deployer"
  - title: "Implement new StandardValidator"
  - title: "Update Superchain Registry"
  - title: "Complete FMA"
  - title: "Complete audits"
  - title: "Add audits to monorepo"
  - title: "Deploy to Alphanet"
  - title: "Deploy to Betanet"
  - title: "Draft governance post"
  - title: "Update Standard Rollup Charter"
  - title: "Roll initial hardfork notification comms"
  - title: "Determine and verify prestates"
  - title: "Write Sepolia superchain-ops task"
  - title: "Post governance post"
  - title: "Cut Sepolia release"
  - title: "Write upgrade notice docs"
  - title: "Roll comms to Sepolia partners"
  - title: "Execute Sepolia superchain-ops task"
  - title: "Roll Sepolia reminder comms"
  - title: "Activate HF on Sepolia"
  - title: "Write mainnet superchain-ops task"
  - title: "Cut mainnet release"
  - title: "Send Foundation approval e-mail"
  - title: "Roll comms to mainnet partners"
  - title: "Complete signing ceremony"
  - title: "Execute mainnet superchain-ops task"
  - title: "Roll mainnet reminder comms"
  - title: "Activate HF on mainnet"
  